name: 'd3_dbt'
version: '1.0.0'
config-version: 2

profile: 'd3_dbt'

model-paths: ["models"]
seed-paths: ["seeds"]
macro-paths: ["macros"]
snapshot-paths: ["snapshots"]
analysis-paths: ["analyses"]
test-paths: ["tests"]

vars:
  dbt_utils_dispatch_list: ["snowflake"]

models:
  d3_dbt:
    staging:
      +materialized: view
      +schema: staging
    intermediate:
      +materialized: view
      +schema: intermediate
    mart:
      +materialized: table
      +schema: mart

seeds:
  d3_dbt:
    +schema: raw_data
    +quote_columns: false
